### ISSUE TITLE
plot and line_plot fail with label arguments

### ISSUE THREAD

**Issue by Rlamboll** [IAMconsortium/pyam#518] opened 2021-04-22 11:26 UTC
Following the most recent update, line_plot, and the new preferred function plot, both now fail when used with "label" arguments, or if used without "color" arguments under very simple circumstances. Minimal coding example: 

import pyam
import pandas as pd
# Define dataframe:
_mc = "model_c"
_sa = "scen_a"
_sb = "scen_b"
_eco2 = "Emissions|CO2"
_gtc = "Gt C/yr"
_ech4 = "Emissions|CH4"
_mtch4 = "Mt CH4/yr"
_msrvu = ["model", "scenario", "region", "variable", "unit"]
simple_df = pd.DataFrame(
    [
        [_mc, 1, "World", _eco2, _gtc, 0, 1000, 5000],
        [_mc, _sb, "World", _eco2, _gtc, 1, 1000, 5000],
        [_mc, _sa, "World", _ech4, _mtch4, 0, 300, 500],
        [_mc, _sb, "World", _ech4, _mtch4, 1, 300, 500],
    ],
    columns=_msrvu + [2010, 2030, 2050],
)
simple_df = pyam.IamDataFrame(simple_df)
# The following fails:
simple_df.filter(variable=_eco2).plot()
# The following works: 
simple_df.filter(variable=_eco2).plot(color='scenario')
# The following both fail: 
simple_df.filter(variable=_eco2).plot(color='scenario', label="sillyString")
simple_df.filter(variable=_eco2).plot(color='scenario', label=["sillyString"])

**Comment by danielhuppmann** [comment] 2021-04-22 13:11
Thank you for raising this issue, @Rlamboll! It also occurs on my machine, but it works (at least) in the [first-steps tutorial](https://pyam-iamc.readthedocs.io/en/stable/tutorials/pyam_first_steps.html), cell [19]...

Might be some update of matplotlib or a corner case with the custom labelling implemented by @gidden a while ago...

**Comment by Rlamboll** [comment] 2021-04-22 13:24
I think all the cases on your tutorial have more than 13 lines so don't use legends.

**Comment by gidden** [comment] 2021-04-26 06:50
Hi both - just took a look at this now. Is there an existing test or example of how this is expected to work? In general, all non-recognized kwargs are passed directly to the underlying plot functions. 

It would also be helpful to get the error logs on these.

**Comment by danielhuppmann** [comment] 2021-04-26 07:26
Apologies, I created a PR with the fix (#519) but didn't specifically respond here...

The issue was caused by the fact that of the scenario names is an integer, not a string, so `str.join(<list of strings>)` failed. The quickfix is to map the column names to string before creating the labels.

I briefly thought about whether to require all columns in a timeseries table to be strings, but there are cases where this doesn't make sense. E.g., when querying non-default scenario versions from an IIASA database, the version number is added as an extra column to `data`, and this should be an integer...

The caveat here is that one could create an IamDataFrame from pandas where some scenarios are named `'1'` (string) and others are `1` (int), and filtering gives you different results depending on the type of the argument given to `df.filter(..)`. But I think this is a corner case that we can't realistically guard against...

**Comment by Rlamboll** [comment] 2021-04-26 09:55
I may have slightly confused issues by including two semi-overlapping issues into one. The second case is actually complaining that it receives two arguments for label - I think you internally generate a label string and append whatever arguments are given to the plot function, without checking for duplicates. When running the above code in the current version of pyam with no numerical scenario names, we still get the following error: "TypeError: PlotAccessor object got multiple values for keyword argument 'label'"

**Comment by danielhuppmann** [comment] 2021-04-26 10:17
Thanks for clarifying - so your expected outcome from the example above would be the following?

```
simple_df.plot(label="foo")
```
![image](https://user-images.githubusercontent.com/16931589/116067213-3aabcc80-a689-11eb-8900-5c5cdefb69d1.png)

**Comment by Rlamboll** [comment] 2021-04-26 10:32
Not really, you seem to have a different color in the legend to in the plot (unless there's a hidden duplicate). My preferred response is to have the last-plotted line given that label. I've only used this in practice when plotting something that happens to have a single color, e.g. cell 12 of https://github.com/GranthamImperial/silicone/blob/master/notebooks/00_Introductory_infilling.ipynb, 
so arguably in this case (plotting two items simultaneously) you might have both line-colors given the input label in the key.

**Comment by danielhuppmann** [comment] 2021-04-26 10:55
Well, this is the data given by you in the illustration above... Yes, it's (almost exactly) two times two over-lapping lines. 

So for the use case above, how about this?
![image](https://user-images.githubusercontent.com/16931589/116071749-8c0a8a80-a68e-11eb-9778-1507fd8b88f5.png)

**Comment by Rlamboll** [comment] 2021-04-26 11:31
Yes, I think that's the best output. Might be worth checking that this doesn't duplicate the legend item if you also give it a color argument to ensure that all the lines are identical

**Comment by danielhuppmann** [comment] 2021-04-26 12:09
Pushed the fix for the second aspect to the PR, explicit `label` is now possible.

Indeed, if you provide both a `label` and an explicit color, the item will be shown several times in the legend - but the code is already so elaborate that I will not fix this corner case.

**Closed** 2021-04-27 07:04 UTC
Labels: bug, dependencies
