### ISSUE TITLE
Non-cyclical conversion between pyam and pandas with metadata

### ISSUE THREAD

**Issue by Rlamboll** [IAMconsortium/pyam#435] opened 2020-10-07 17:30 UTC
Now that we have to convert back and forth between pandas and pyam to make a general changes in the dataframe, it would be good for there to be  a way where this gives us back exactly what we start with. Currently, metadata is either lost or converted to an additional column by default, depending on whether one uses the .data or the .as_pandas() commands. The latter feels like it should allow for a cyclical transform, probably by default but certainly as an option. This could be done by, e.g. putting "\_meta\_" in front of meta columns when converting to a pd, then checking the pds read in for columns starting in this way. 

Example of how this doesn't work currently: 

import pyam
import pandas as pd
_mc = "model_c"
_sa = "scen_a"
_sb = "scen_b"
_eco2 = "Emissions|CO2"
_gtc = "Gt C/yr"
_ech4 = "Emissions|CH4"
_mtch4 = "Mt CH4/yr"
_msrvu = ["model", "scenario", "region", "variable", "unit"]
simple_df = pd.DataFrame(
    [
        [_mc, _sa, "World", _eco2, _gtc, 0, 1000, 5000],
        [_mc, _sb, "World", _eco2, _gtc, 1, 1000, 5000],
        [_mc, _sa, "World", _ech4, _mtch4, 0, 300, 500],
        [_mc, _sb, "World", _ech4, _mtch4, 1, 300, 500],
    ],
    columns=_msrvu + [2010, 2030, 2050],
)
simple_df = pyam.IamDataFrame(simple_df)
simple_df.set_meta(meta="Not funny", name="jokes")
simple_df.meta
# metadata exists
simple_df = pyam.IamDataFrame(simple_df.as_pandas())
simple_df.meta
# The metadata has become data

**Comment by danielhuppmann** [comment] 2020-10-07 20:02
We had this discussion before, I think that the way you are operating directly on the timeseries `data` dataframe is not how the package was intended to be used...

Anyway, you can pass `data` and `meta` separately when instantiating a new **IamDataFrame** instance:
```
copy_df = pyam.IamDataFrame(data=simple_df.data, meta=simple_df.meta)
```

**Comment by danielhuppmann** [comment] 2021-06-10 17:38
Closing as there have been no further comments for ~9 months following my comment.

**Closed by danielhuppmann** 2021-06-10 17:38 UTC
